language: node_js
node_js: 12
cache: node_modules

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $token
  keep_history: true
  local_dir: dist
  on:
    branch: master
